version: "3.4"

services:
  indexer-mysql:
    image: bitnami/mysql:latest
    container_name: indexer-mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: indexer
    volumes:
      - dolphinscheduler-postgresql:/bitnami/postgresql
      - dolphinscheduler-postgresql-initdb:/docker-entrypoint-initdb.d
    networks:
      - indexer

networks:
  indexer:
    driver: bridge