apollo:
  meta: http://dev.config.xinc818.com:8080

## datasource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://test-xc-dev.mysql.rds.aliyuncs.com:3331/data_service?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: test_xc_dev
      password: x!c@_d#ev$xcD_SdeAvM
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,wall,slf4j
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      initial-size: 5
      min-idle: 5
      max-wait: 10000
      max-active: 20
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      filter:
        stat:
          slow-sql-millis: 10
          log-slow-sql: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        reset-enable: true
        login-username: admin
        login-password: "%*XCVSs3461dfs$#"